static const Command_Spec g_commands_find[] = {
    CMD("find_package", eval_find_package),
    CMD("find_file", eval_find_file_command),
    CMD("find_path", eval_find_path_command),
    CMD("find_program", eval_find_program_command),
    CMD("find_library", eval_find_library_command),
    CMD("find_package_handle_standard_args", eval_find_package_handle_standard_args_command),
    CMD("cmake_pkg_config", eval_cmake_pkg_config_command),
    CMD("pkg_check_modules", eval_pkg_check_modules_command),
    CMD("pkg_search_module", eval_pkg_search_module_command),
    CMD("check_symbol_exists", eval_check_symbol_exists_command),
    CMD("check_function_exists", eval_check_function_exists_command),
    CMD("check_include_file", eval_check_include_file_command),
    CMD("check_include_files", eval_check_include_files_command),
    CMD("check_type_size", eval_check_type_size_command),
    CMD("check_c_compiler_flag", eval_check_c_compiler_flag_command),
    CMD("check_struct_has_member", eval_check_struct_has_member_command),
    CMD("check_c_source_compiles", eval_check_c_source_compiles_command),
    CMD("check_library_exists", eval_check_library_exists_command),
    CMD("check_c_source_runs", eval_check_c_source_runs_command),
    CMD("try_compile", eval_try_compile_command),
    CMD("try_run", eval_try_run_command),
    CMD("execute_process", eval_execute_process_command),
    CMD("exec_program", eval_exec_program_command),
    CMD("load_command", eval_load_command_command),
};
