#@@CASE cmake_path_extended_surface_matches_local_seed
#@@OUTCOME SUCCESS
#@@QUERY VAR P_EXT
#@@QUERY VAR P_EXT_LAST
#@@QUERY VAR P_STEM
#@@QUERY VAR P_STEM_LAST
#@@QUERY VAR P_APPEND_S
#@@QUERY VAR P_RMF
#@@QUERY VAR P_REPF
#@@QUERY VAR P_REPEXT
#@@QUERY VAR P_REL
#@@QUERY VAR P_ABS
#@@QUERY VAR P_NATIVE
#@@QUERY VAR P_NATIVE_LEN
#@@QUERY VAR P_CMP_EQ
#@@QUERY VAR P_CMP_NEQ
#@@QUERY VAR P_HAS_ROOT_NAME
#@@QUERY VAR P_HAS_ROOT_DIRECTORY
#@@QUERY VAR P_HAS_ROOT_PATH
#@@QUERY VAR P_HAS_FILENAME
#@@QUERY VAR P_HAS_EXTENSION
#@@QUERY VAR P_HAS_STEM
#@@QUERY VAR P_HAS_RELATIVE_PART
#@@QUERY VAR P_HAS_PARENT_PATH
#@@QUERY VAR P_IS_ABSOLUTE
#@@QUERY VAR P_IS_RELATIVE
#@@QUERY VAR P_PREFIX_OK
#@@QUERY VAR P_PREFIX_NORM
#@@QUERY VAR P_PREFIX_BAD
#@@QUERY VAR P_NORM
cmake_path(SET P NORMALIZE "/srv/./share/dir/../file.tar.gz")
cmake_path(GET P EXTENSION P_EXT)
cmake_path(GET P EXTENSION LAST_ONLY P_EXT_LAST)
cmake_path(GET P STEM P_STEM)
cmake_path(GET P STEM LAST_ONLY P_STEM_LAST)
cmake_path(APPEND P sub OUTPUT_VARIABLE P_APPEND)
cmake_path(APPEND_STRING P_APPEND .meta OUTPUT_VARIABLE P_APPEND_S)
cmake_path(REMOVE_FILENAME P_APPEND_S OUTPUT_VARIABLE P_RMF)
cmake_path(REPLACE_FILENAME P_APPEND_S repl.txt OUTPUT_VARIABLE P_REPF)
cmake_path(REMOVE_EXTENSION P_REPF LAST_ONLY OUTPUT_VARIABLE P_NOEXT)
cmake_path(REPLACE_EXTENSION P_NOEXT .log OUTPUT_VARIABLE P_REPEXT)
cmake_path(NORMAL_PATH P_REPEXT OUTPUT_VARIABLE P_NORM)
cmake_path(RELATIVE_PATH P_NORM BASE_DIRECTORY /srv OUTPUT_VARIABLE P_REL)
cmake_path(ABSOLUTE_PATH P_REL BASE_DIRECTORY /srv NORMALIZE OUTPUT_VARIABLE P_ABS)
cmake_path(NATIVE_PATH P_ABS P_NATIVE)
cmake_path(CONVERT "a;b;c" TO_NATIVE_PATH_LIST P_NATIVE_LIST)
cmake_path(SET P_ROOTED "/srv/share/dir/file.tar.gz")
cmake_path(HAS_ROOT_NAME P_ROOTED P_HAS_ROOT_NAME)
cmake_path(HAS_ROOT_DIRECTORY P_ROOTED P_HAS_ROOT_DIRECTORY)
cmake_path(HAS_ROOT_PATH P_ROOTED P_HAS_ROOT_PATH)
cmake_path(HAS_FILENAME P_ROOTED P_HAS_FILENAME)
cmake_path(HAS_EXTENSION P_ROOTED P_HAS_EXTENSION)
cmake_path(HAS_STEM P_ROOTED P_HAS_STEM)
cmake_path(HAS_RELATIVE_PART P_ROOTED P_HAS_RELATIVE_PART)
cmake_path(HAS_PARENT_PATH P_ROOTED P_HAS_PARENT_PATH)
cmake_path(IS_ABSOLUTE P_ROOTED P_IS_ABSOLUTE)
cmake_path(SET P_REL_ONLY rel/part)
cmake_path(IS_RELATIVE P_REL_ONLY P_IS_RELATIVE)
cmake_path(SET P_PREFIX "/srv/share")
cmake_path(IS_PREFIX P_PREFIX "/srv/share/dir/file.tar.gz" P_PREFIX_OK)
cmake_path(IS_PREFIX P_PREFIX "/srv/share/dir/../dir/file.tar.gz" NORMALIZE P_PREFIX_NORM)
cmake_path(IS_PREFIX P_PREFIX "/srv/other/file.tar.gz" P_PREFIX_BAD)
string(LENGTH "${P_NATIVE_LIST}" P_NATIVE_LEN)
cmake_path(COMPARE "/srv//share" EQUAL "/srv/share" P_CMP_EQ)
cmake_path(COMPARE "/srv/share" NOT_EQUAL "/srv/other" P_CMP_NEQ)
#@@ENDCASE

#@@CASE cmake_path_getters_and_roundtrip_cover_remaining_components
#@@OUTCOME SUCCESS
#@@QUERY VAR P_ROOT_NAME
#@@QUERY VAR P_ROOT_DIR
#@@QUERY VAR P_ROOT_PATH
#@@QUERY VAR P_FILENAME
#@@QUERY VAR P_RELATIVE_PART
#@@QUERY VAR P_PARENT_PATH
#@@QUERY VAR P_ABS
#@@QUERY VAR P_REL_AGAIN
#@@QUERY VAR P_REL_HAS_ROOT_PATH
#@@QUERY VAR P_ROOT_HAS_FILENAME
#@@QUERY VAR P_CANON_EQ
cmake_path(SET P_DRV "/alpha/beta/file.name.ext")
cmake_path(GET P_DRV ROOT_NAME P_ROOT_NAME)
cmake_path(GET P_DRV ROOT_DIRECTORY P_ROOT_DIR)
cmake_path(GET P_DRV ROOT_PATH P_ROOT_PATH)
cmake_path(GET P_DRV FILENAME P_FILENAME)
cmake_path(GET P_DRV RELATIVE_PART P_RELATIVE_PART)
cmake_path(GET P_DRV PARENT_PATH P_PARENT_PATH)
cmake_path(SET P_REL "alpha/./beta")
cmake_path(ABSOLUTE_PATH P_REL BASE_DIRECTORY "/base" NORMALIZE OUTPUT_VARIABLE P_ABS)
cmake_path(RELATIVE_PATH P_ABS BASE_DIRECTORY "/base" OUTPUT_VARIABLE P_REL_AGAIN)
cmake_path(HAS_ROOT_PATH P_REL P_REL_HAS_ROOT_PATH)
cmake_path(SET P_ROOT_ONLY "/")
cmake_path(HAS_FILENAME P_ROOT_ONLY P_ROOT_HAS_FILENAME)
cmake_path(COMPARE "/alpha//beta" EQUAL "/alpha/beta" P_CANON_EQ)
#@@ENDCASE

#@@CASE cmake_path_invalid_get_component_errors
#@@OUTCOME ERROR
cmake_path(SET P value)
cmake_path(GET P BAD_COMPONENT P_BAD)
#@@ENDCASE
