#@@CASE directory_usage_directory_mutations_propagate_to_existing_and_future_targets
#@@OUTCOME SUCCESS
#@@FILE before.c
#@@FILE after.c
#@@QUERY VAR DIR_DEFS
#@@QUERY VAR DIR_OPTS_HAS_WALL
#@@QUERY VAR DIR_OPTS_HAS_INVALID_PCH
#@@QUERY VAR DIR_LINK_OPTS_HAS_Z
#@@QUERY VAR DIR_LINK_OPTS_HAS_DEFS
#@@QUERY VAR DIR_LINK_OPTS_HAS_PTHREAD
#@@QUERY VAR DIR_INCS_HAS_LOCAL
#@@QUERY VAR DIR_INCS_HAS_PUB
#@@QUERY VAR DIR_LINK_DIRS_HAS_LOCAL
#@@QUERY VAR DIR_LINK_DIRS_HAS_PUB
#@@QUERY VAR DIR_LINK_LIBS_HAS_DBG
#@@QUERY VAR DIR_LINK_LIBS_HAS_OPT
#@@QUERY VAR DIR_LINK_LIBS_HAS_GEN
#@@QUERY VAR DIR_LINK_LIBS_HAS_PLAIN
#@@QUERY VAR BEFORE_INCS_HAS_LOCAL
#@@QUERY VAR BEFORE_INCS_HAS_PUB
#@@QUERY VAR AFTER_OPTS_HAS_WALL
#@@QUERY VAR AFTER_OPTS_HAS_INVALID_PCH
#@@QUERY VAR AFTER_LINK_OPTS_HAS_Z
#@@QUERY VAR AFTER_LINK_OPTS_HAS_PTHREAD
#@@QUERY VAR AFTER_INCS_HAS_LOCAL
#@@QUERY VAR AFTER_INCS_HAS_PUB
#@@QUERY VAR AFTER_LINK_DIRS_HAS_LOCAL
#@@QUERY VAR AFTER_LINK_DIRS_HAS_PUB
#@@QUERY VAR AFTER_LINK_LIBS_HAS_DBG
#@@QUERY VAR AFTER_LINK_LIBS_HAS_OPT
#@@QUERY VAR AFTER_LINK_LIBS_HAS_GEN
#@@QUERY VAR AFTER_LINK_LIBS_HAS_PLAIN
add_library(dir_before SHARED before.c)
add_compile_definitions(FOO BAR=1)
add_compile_options("SHELL:-Wall -Winvalid-pch" -Winvalid-pch)
add_link_options("LINKER:-z,defs" "SHELL:-pthread -pthread")
include_directories(BEFORE SYSTEM inc/local inc/pub)
link_directories(BEFORE lib/local lib/pub)
add_definitions(-DLEGACY=1 -fPIC)
remove_definitions(-DLEGACY=1)
link_libraries(debug dbg optimized opt general gen plain)
get_property(DIR_DEFS DIRECTORY PROPERTY COMPILE_DEFINITIONS)
get_property(DIR_OPTS DIRECTORY PROPERTY COMPILE_OPTIONS)
get_property(DIR_LINK_OPTS DIRECTORY PROPERTY LINK_OPTIONS)
get_property(DIR_INCS DIRECTORY PROPERTY INCLUDE_DIRECTORIES)
get_property(DIR_LINK_DIRS DIRECTORY PROPERTY LINK_DIRECTORIES)
get_property(DIR_LINK_LIBS DIRECTORY PROPERTY LINK_LIBRARIES)
add_library(dir_after SHARED after.c)
get_target_property(BEFORE_INCS dir_before INCLUDE_DIRECTORIES)
get_target_property(AFTER_OPTS dir_after COMPILE_OPTIONS)
get_target_property(AFTER_LINK_OPTS dir_after LINK_OPTIONS)
get_target_property(AFTER_INCS dir_after INCLUDE_DIRECTORIES)
get_target_property(AFTER_LINK_DIRS dir_after LINK_DIRECTORIES)
get_target_property(AFTER_LINK_LIBS dir_after LINK_LIBRARIES)
string(FIND "${DIR_OPTS}" "-Wall" DIR_OPTS_HAS_WALL_POS)
string(FIND "${DIR_OPTS}" "-Winvalid-pch" DIR_OPTS_HAS_INVALID_PCH_POS)
string(FIND "${DIR_LINK_OPTS}" "-z" DIR_LINK_OPTS_HAS_Z_POS)
string(FIND "${DIR_LINK_OPTS}" "defs" DIR_LINK_OPTS_HAS_DEFS_POS)
string(FIND "${DIR_LINK_OPTS}" "-pthread" DIR_LINK_OPTS_HAS_PTHREAD_POS)
string(FIND "${DIR_INCS}" "inc/local" DIR_INCS_HAS_LOCAL_POS)
string(FIND "${DIR_INCS}" "inc/pub" DIR_INCS_HAS_PUB_POS)
string(FIND "${DIR_LINK_DIRS}" "lib/local" DIR_LINK_DIRS_HAS_LOCAL_POS)
string(FIND "${DIR_LINK_DIRS}" "lib/pub" DIR_LINK_DIRS_HAS_PUB_POS)
string(FIND "${DIR_LINK_LIBS}" "dbg" DIR_LINK_LIBS_HAS_DBG_POS)
string(FIND "${DIR_LINK_LIBS}" "opt" DIR_LINK_LIBS_HAS_OPT_POS)
string(FIND "${DIR_LINK_LIBS}" "gen" DIR_LINK_LIBS_HAS_GEN_POS)
string(FIND "${DIR_LINK_LIBS}" "plain" DIR_LINK_LIBS_HAS_PLAIN_POS)
string(FIND "${BEFORE_INCS}" "inc/local" BEFORE_INCS_HAS_LOCAL_POS)
string(FIND "${BEFORE_INCS}" "inc/pub" BEFORE_INCS_HAS_PUB_POS)
string(FIND "${AFTER_OPTS}" "-Wall" AFTER_OPTS_HAS_WALL_POS)
string(FIND "${AFTER_OPTS}" "-Winvalid-pch" AFTER_OPTS_HAS_INVALID_PCH_POS)
string(FIND "${AFTER_LINK_OPTS}" "-z" AFTER_LINK_OPTS_HAS_Z_POS)
string(FIND "${AFTER_LINK_OPTS}" "-pthread" AFTER_LINK_OPTS_HAS_PTHREAD_POS)
string(FIND "${AFTER_INCS}" "inc/local" AFTER_INCS_HAS_LOCAL_POS)
string(FIND "${AFTER_INCS}" "inc/pub" AFTER_INCS_HAS_PUB_POS)
string(FIND "${AFTER_LINK_DIRS}" "lib/local" AFTER_LINK_DIRS_HAS_LOCAL_POS)
string(FIND "${AFTER_LINK_DIRS}" "lib/pub" AFTER_LINK_DIRS_HAS_PUB_POS)
string(FIND "${AFTER_LINK_LIBS}" "dbg" AFTER_LINK_LIBS_HAS_DBG_POS)
string(FIND "${AFTER_LINK_LIBS}" "opt" AFTER_LINK_LIBS_HAS_OPT_POS)
string(FIND "${AFTER_LINK_LIBS}" "gen" AFTER_LINK_LIBS_HAS_GEN_POS)
string(FIND "${AFTER_LINK_LIBS}" "plain" AFTER_LINK_LIBS_HAS_PLAIN_POS)
foreach(VAR
    DIR_OPTS_HAS_WALL
    DIR_OPTS_HAS_INVALID_PCH
    DIR_LINK_OPTS_HAS_Z
    DIR_LINK_OPTS_HAS_DEFS
    DIR_LINK_OPTS_HAS_PTHREAD
    DIR_INCS_HAS_LOCAL
    DIR_INCS_HAS_PUB
    DIR_LINK_DIRS_HAS_LOCAL
    DIR_LINK_DIRS_HAS_PUB
    DIR_LINK_LIBS_HAS_DBG
    DIR_LINK_LIBS_HAS_OPT
    DIR_LINK_LIBS_HAS_GEN
    DIR_LINK_LIBS_HAS_PLAIN
    BEFORE_INCS_HAS_LOCAL
    BEFORE_INCS_HAS_PUB
    AFTER_OPTS_HAS_WALL
    AFTER_OPTS_HAS_INVALID_PCH
    AFTER_LINK_OPTS_HAS_Z
    AFTER_LINK_OPTS_HAS_PTHREAD
    AFTER_INCS_HAS_LOCAL
    AFTER_INCS_HAS_PUB
    AFTER_LINK_DIRS_HAS_LOCAL
    AFTER_LINK_DIRS_HAS_PUB
    AFTER_LINK_LIBS_HAS_DBG
    AFTER_LINK_LIBS_HAS_OPT
    AFTER_LINK_LIBS_HAS_GEN
    AFTER_LINK_LIBS_HAS_PLAIN)
  if(${VAR}_POS EQUAL -1)
    set(${VAR} 0)
  else()
    set(${VAR} 1)
  endif()
endforeach()
#@@ENDCASE

#@@CASE directory_usage_link_libraries_rejects_dangling_qualifier
#@@OUTCOME ERROR
link_libraries(debug)
#@@ENDCASE
