#@@CASE file_host_effect_download_surface
#@@OUTCOME SUCCESS
#@@QUERY FILE_TEXT build/download_out.txt
#@@QUERY FILE_SHA256 build/download_out.txt
#@@QUERY VAR DL_STATUS_LEN
#@@QUERY VAR DL_STATUS_CODE
#@@QUERY VAR DL_LOG_NONEMPTY
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/download_src.txt" "hello")
file(SHA256 "${CMAKE_CURRENT_SOURCE_DIR}/download_src.txt" DL_HASH)
set(DL_URL "file://${CMAKE_CURRENT_SOURCE_DIR}/download_src.txt")
file(DOWNLOAD
  "${DL_URL}"
  "${CMAKE_CURRENT_BINARY_DIR}/download_out.txt"
  EXPECTED_HASH "SHA256=${DL_HASH}"
  STATUS DL_STATUS
  LOG DL_LOG)
list(LENGTH DL_STATUS DL_STATUS_LEN)
list(GET DL_STATUS 0 DL_STATUS_CODE)
string(LENGTH "${DL_LOG}" DL_LOG_LEN)
if(DL_LOG_LEN GREATER 0)
  set(DL_LOG_NONEMPTY 1)
else()
  set(DL_LOG_NONEMPTY 0)
endif()
#@@ENDCASE

#@@CASE file_host_effect_download_range_start_beyond_source_surface
#@@OUTCOME SUCCESS
#@@QUERY FILE_TEXT build/range_out.txt
#@@QUERY VAR RANGE_STATUS_LEN
#@@QUERY VAR RANGE_STATUS_CODE
#@@QUERY VAR RANGE_STATUS_MSG
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/range_src.txt" "abc")
file(DOWNLOAD
  "file://${CMAKE_CURRENT_SOURCE_DIR}/range_src.txt"
  "${CMAKE_CURRENT_BINARY_DIR}/range_out.txt"
  RANGE_START 99
  STATUS RANGE_STATUS
  LOG RANGE_LOG)
list(LENGTH RANGE_STATUS RANGE_STATUS_LEN)
list(GET RANGE_STATUS 0 RANGE_STATUS_CODE)
list(GET RANGE_STATUS 1 RANGE_STATUS_MSG)
#@@ENDCASE

#@@CASE file_host_effect_transfer_error_status_surface
#@@OUTCOME SUCCESS
#@@QUERY FILE_EXISTS build/missing_download_out.txt
#@@QUERY FILE_EXISTS build/missing_upload_parent/uploaded.txt
#@@QUERY VAR DL_MISS_STATUS_LEN
#@@QUERY VAR DL_MISS_STATUS_CODE
#@@QUERY VAR DL_MISS_LOG_NONEMPTY
#@@QUERY VAR UP_FAIL_STATUS_LEN
#@@QUERY VAR UP_FAIL_STATUS_CODE
#@@QUERY VAR UP_FAIL_LOG_NONEMPTY
file(DOWNLOAD
  "file://${CMAKE_CURRENT_SOURCE_DIR}/missing_download_src.txt"
  "${CMAKE_CURRENT_BINARY_DIR}/missing_download_out.txt"
  STATUS DL_MISS_STATUS
  LOG DL_MISS_LOG)
list(LENGTH DL_MISS_STATUS DL_MISS_STATUS_LEN)
list(GET DL_MISS_STATUS 0 DL_MISS_STATUS_CODE)
string(LENGTH "${DL_MISS_LOG}" DL_MISS_LOG_LEN)
if(DL_MISS_LOG_LEN GREATER 0)
  set(DL_MISS_LOG_NONEMPTY 1)
else()
  set(DL_MISS_LOG_NONEMPTY 0)
endif()
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/upload_src.txt" "upload")
file(UPLOAD
  "${CMAKE_CURRENT_SOURCE_DIR}/upload_src.txt"
  "file://${CMAKE_CURRENT_BINARY_DIR}/missing_upload_parent/uploaded.txt"
  STATUS UP_FAIL_STATUS
  LOG UP_FAIL_LOG)
list(LENGTH UP_FAIL_STATUS UP_FAIL_STATUS_LEN)
list(GET UP_FAIL_STATUS 0 UP_FAIL_STATUS_CODE)
string(LENGTH "${UP_FAIL_LOG}" UP_FAIL_LOG_LEN)
if(UP_FAIL_LOG_LEN GREATER 0)
  set(UP_FAIL_LOG_NONEMPTY 1)
else()
  set(UP_FAIL_LOG_NONEMPTY 0)
endif()
#@@ENDCASE

#@@CASE file_host_effect_archive_surface
#@@OUTCOME SUCCESS
#@@QUERY FILE_EXISTS build/sample.tar
#@@QUERY TREE build/archive_out
file(MAKE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/archive_input/sub")
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/archive_input/a.txt" "A")
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/archive_input/sub/b.txt" "B")
file(ARCHIVE_CREATE
  OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/sample.tar"
  PATHS "${CMAKE_CURRENT_SOURCE_DIR}/archive_input"
  FORMAT paxr
  MTIME 0)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/archive_out")
file(ARCHIVE_EXTRACT
  INPUT "${CMAKE_CURRENT_BINARY_DIR}/sample.tar"
  DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/archive_out")
#@@ENDCASE

#@@CASE file_host_effect_archive_zip_surface
#@@OUTCOME SUCCESS
#@@QUERY FILE_EXISTS build/sample.zip
#@@QUERY TREE build/zip_out
file(MAKE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/zip_input/sub")
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/zip_input/a.txt" "ZA")
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/zip_input/sub/b.txt" "ZB")
file(ARCHIVE_CREATE
  OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/sample.zip"
  PATHS "${CMAKE_CURRENT_SOURCE_DIR}/zip_input"
  FORMAT zip)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/zip_out")
file(ARCHIVE_EXTRACT
  INPUT "${CMAKE_CURRENT_BINARY_DIR}/sample.zip"
  DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/zip_out")
#@@ENDCASE

#@@CASE file_host_effect_generate_lock_and_runtime_deps_surface
#@@OUTCOME SUCCESS
#@@QUERY FILE_TEXT build/gen_out.txt
#@@QUERY FILE_EXISTS build/lock_dir/cmake.lock
#@@QUERY VAR LOCK_RES
#@@QUERY VAR UNLOCK_RES
#@@QUERY VAR RD_RES_LEN
#@@QUERY VAR RD_UNRES_LEN
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/gen_out.txt" CONTENT "OUT")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/lock_dir")
file(LOCK "${CMAKE_CURRENT_BINARY_DIR}/lock_dir" DIRECTORY RESULT_VARIABLE LOCK_RES)
file(LOCK "${CMAKE_CURRENT_BINARY_DIR}/lock_dir" DIRECTORY RELEASE RESULT_VARIABLE UNLOCK_RES)
file(GET_RUNTIME_DEPENDENCIES
  RESOLVED_DEPENDENCIES_VAR RD_RES
  UNRESOLVED_DEPENDENCIES_VAR RD_UNRES
  EXECUTABLES "${CMAKE_COMMAND}")
list(LENGTH RD_RES RD_RES_LEN)
list(LENGTH RD_UNRES RD_UNRES_LEN)
#@@ENDCASE

#@@CASE file_host_effect_invalid_forms
#@@OUTCOME ERROR
file(ARCHIVE_CREATE OUTPUT)
file(ARCHIVE_EXTRACT INPUT)
file(LOCK)
#@@ENDCASE
