#@@CASE list_transform_genex_strip_and_output_variable
#@@OUTCOME SUCCESS
#@@QUERY VAR L
#@@QUERY VAR L_STRIPPED
#@@QUERY VAR L_APPENDED
set(L "$<CONFIG:Debug>;a$<IF:$<BOOL:1>,b,c>;x")
list(TRANSFORM L GENEX_STRIP OUTPUT_VARIABLE L_STRIPPED)
list(TRANSFORM L APPEND "_S" AT 0 OUTPUT_VARIABLE L_APPENDED)
#@@ENDCASE

#@@CASE list_sort_and_transform_selector_surface_matches_documented_combinations
#@@OUTCOME SUCCESS
#@@QUERY VAR SORT_NAT
#@@QUERY VAR SORT_BASE
#@@QUERY VAR L
#@@QUERY VAR L_AT
#@@QUERY VAR L_FOR
#@@QUERY VAR L_REGEX
#@@QUERY VAR L_REPLACE_REGEX
set(SORT_NAT "a10;a2;A1")
list(SORT SORT_NAT COMPARE NATURAL CASE INSENSITIVE)
set(SORT_BASE "/tmp/A2.txt;/tmp/a1.txt;/tmp/b10.txt")
list(SORT SORT_BASE COMPARE FILE_BASENAME CASE INSENSITIVE ORDER DESCENDING)
set(L "  one  ;two;three;four")
list(TRANSFORM L STRIP AT 0 OUTPUT_VARIABLE L_AT)
list(TRANSFORM L APPEND _X FOR 1 3 2 OUTPUT_VARIABLE L_FOR)
list(TRANSFORM L TOUPPER REGEX "^t" OUTPUT_VARIABLE L_REGEX)
list(TRANSFORM L REPLACE "o" "O" REGEX "^t" OUTPUT_VARIABLE L_REPLACE_REGEX)
#@@ENDCASE

#@@CASE list_transform_output_variable_requires_single_output_var
#@@OUTCOME ERROR
set(L "a;b")
list(TRANSFORM L TOUPPER OUTPUT_VARIABLE)
#@@ENDCASE
