#@@CASE top_level_project_signature_and_policy_surface
#@@OUTCOME SUCCESS
#@@PROJECT_LAYOUT RAW_CMAKELISTS
#@@ENV DIFF_TOP_ENV=env-hit
#@@ENV_UNSET DIFF_TOP_ENV_CLEARED
#@@CACHE_INIT DIFF_TOP_CACHE:STRING=cache-hit
#@@FILE_TEXT build/prelude.cmake
set(PRELUDE_MARKER prelude-hit)
#@@END_FILE_TEXT
#@@QUERY VAR CMAKE_MINIMUM_REQUIRED_VERSION
#@@QUERY VAR POLICY_CMP0048
#@@QUERY VAR PROJECT_NAME
#@@QUERY VAR PROJECT_VERSION
#@@QUERY VAR PROJECT_DESCRIPTION
#@@QUERY VAR PROJECT_HOMEPAGE_URL
#@@QUERY VAR PROJECT_TOP_LEVEL_NORM
#@@QUERY VAR RAWPROJ_TOP_LEVEL_NORM
#@@QUERY VAR CMAKE_PROJECT_NAME
#@@QUERY VAR CMAKE_PROJECT_VERSION
#@@QUERY VAR DIFF_TOP_ENV_SEEN
#@@QUERY VAR DIFF_TOP_ENV_CLEARED_SEEN
#@@QUERY VAR DIFF_TOP_CACHE_SEEN
#@@QUERY VAR PRELUDE_MARKER
#@@QUERY FILE_TEXT build/prelude.cmake
cmake_minimum_required(VERSION 3.28)
cmake_policy(GET CMP0048 POLICY_CMP0048)
project(RawProj VERSION 1.2.3 DESCRIPTION rootdesc HOMEPAGE_URL https://root LANGUAGES NONE)
if(PROJECT_IS_TOP_LEVEL)
  set(PROJECT_TOP_LEVEL_NORM 1)
else()
  set(PROJECT_TOP_LEVEL_NORM 0)
endif()
if(RawProj_IS_TOP_LEVEL)
  set(RAWPROJ_TOP_LEVEL_NORM 1)
else()
  set(RAWPROJ_TOP_LEVEL_NORM 0)
endif()
set(DIFF_TOP_ENV_SEEN "$ENV{DIFF_TOP_ENV}")
if(DEFINED ENV{DIFF_TOP_ENV_CLEARED})
  set(DIFF_TOP_ENV_CLEARED_SEEN set)
else()
  set(DIFF_TOP_ENV_CLEARED_SEEN unset)
endif()
set(DIFF_TOP_CACHE_SEEN "${DIFF_TOP_CACHE}")
include("${CMAKE_BINARY_DIR}/prelude.cmake")
#@@ENDCASE

#@@CASE top_level_project_cmp0048_new_and_old_without_version
#@@OUTCOME SUCCESS
#@@PROJECT_LAYOUT RAW_CMAKELISTS
#@@QUERY VAR NEW_VER
#@@QUERY VAR NEW_MAJ
#@@QUERY VAR OLD_VER
#@@QUERY VAR OLD_MAJ
cmake_minimum_required(VERSION 3.28)
cmake_policy(SET CMP0048 NEW)
set(PROJECT_VERSION stale)
set(PROJECT_VERSION_MAJOR stale_major)
project(NewNoVer LANGUAGES NONE)
set(NEW_VER "${PROJECT_VERSION}")
set(NEW_MAJ "${PROJECT_VERSION_MAJOR}")
cmake_policy(SET CMP0048 OLD)
set(PROJECT_VERSION keep)
set(PROJECT_VERSION_MAJOR keep_major)
project(OldNoVer LANGUAGES NONE)
set(OLD_VER "${PROJECT_VERSION}")
set(OLD_MAJ "${PROJECT_VERSION_MAJOR}")
#@@ENDCASE

#@@CASE top_level_project_invalid_signature_form
#@@OUTCOME ERROR
#@@PROJECT_LAYOUT RAW_CMAKELISTS
cmake_minimum_required(VERSION 3.28)
project(BadUnexpected VERSION 1.0 C)
#@@ENDCASE
