static const Command_Spec g_commands_control[] = {
    CMD("set", eval_set_command),
    CMD("unset", eval_unset_command),
    CMD("option", eval_option_command),
    CMD("cmake_dependent_option", eval_cmake_dependent_option_command),
    CMD("cmake_minimum_required", eval_cmake_minimum_required_command),
    CMD("project", eval_project_command),
    CMD("message", eval_message_command),
    CMD("list", eval_list_command),
    CMD("string", eval_string_command),
    CMD("math", eval_math_command),
    CMD("cmake_path", eval_cmake_path_command),
    CMD("get_filename_component", eval_get_filename_component_command),
    CMD("include", eval_include_command),
    CMD("include_regular_expression", eval_include_regular_expression_command),
    CMD("enable_language", eval_enable_language_command),
    CMD("site_name", eval_site_name_command),
    CMD("separate_arguments", eval_separate_arguments_command),
    CMD("cmake_push_check_state", eval_cmake_push_check_state_command),
    CMD("cmake_pop_check_state", eval_cmake_pop_check_state_command),
    CMD("cmake_file_api", eval_cmake_file_api_command),
    CMD("cmake_instrumentation", eval_cmake_instrumentation_command),
    CMD("build_command", eval_build_command_command),
};
