#ifndef BUILD_MODEL_QUERY_INTERNAL_H_
#define BUILD_MODEL_QUERY_INTERNAL_H_

#include "build_model_internal.h"

typedef enum {
    BM_EFFECTIVE_INCLUDE_DIRECTORIES = 0,
    BM_EFFECTIVE_COMPILE_DEFINITIONS,
    BM_EFFECTIVE_COMPILE_OPTIONS,
    BM_EFFECTIVE_COMPILE_FEATURES,
    BM_EFFECTIVE_LINK_LIBRARIES,
    BM_EFFECTIVE_LINK_OPTIONS,
    BM_EFFECTIVE_LINK_DIRECTORIES,
} BM_Effective_Query_Kind;

#endif // BUILD_MODEL_QUERY_INTERNAL_H_
