function(nob_diff_report_reset path)
  get_filename_component(_nob_diff_dir "${path}" DIRECTORY)
  if(NOT "${_nob_diff_dir}" STREQUAL "")
    file(MAKE_DIRECTORY "${_nob_diff_dir}")
  endif()
  file(WRITE "${path}" "")
endfunction()

function(nob_diff_normalize_value out value)
  set(_nob_diff_value "${value}")
  string(REPLACE "\\" "/" _nob_diff_value "${_nob_diff_value}")
  if(NOT "${CMAKE_SOURCE_DIR}" STREQUAL "")
    string(REPLACE "${CMAKE_SOURCE_DIR}" "<SRC>" _nob_diff_value "${_nob_diff_value}")
  endif()
  if(NOT "${CMAKE_BINARY_DIR}" STREQUAL "")
    string(REPLACE "${CMAKE_BINARY_DIR}" "<BIN>" _nob_diff_value "${_nob_diff_value}")
  endif()
  if(NOT "${CMAKE_CURRENT_SOURCE_DIR}" STREQUAL "")
    string(REPLACE "${CMAKE_CURRENT_SOURCE_DIR}" "<CUR_SRC>" _nob_diff_value "${_nob_diff_value}")
  endif()
  if(NOT "${CMAKE_CURRENT_BINARY_DIR}" STREQUAL "")
    string(REPLACE "${CMAKE_CURRENT_BINARY_DIR}" "<CUR_BIN>" _nob_diff_value "${_nob_diff_value}")
  endif()
  if(NOT "${CMAKE_CURRENT_LIST_DIR}" STREQUAL "")
    string(REPLACE "${CMAKE_CURRENT_LIST_DIR}" "<LIST_DIR>" _nob_diff_value "${_nob_diff_value}")
  endif()
  if(NOT "${CMAKE_CURRENT_LIST_FILE}" STREQUAL "")
    string(REPLACE "${CMAKE_CURRENT_LIST_FILE}" "<LIST_FILE>" _nob_diff_value "${_nob_diff_value}")
  endif()
  set(${out} "${_nob_diff_value}" PARENT_SCOPE)
endfunction()

function(nob_diff_bool out)
  set(_nob_diff_bool_value "${ARGN}")
  if("${_nob_diff_bool_value}" STREQUAL "")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" STREQUAL "0")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" STREQUAL "FALSE")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" STREQUAL "OFF")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" STREQUAL "NO")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" STREQUAL "N")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" STREQUAL "IGNORE")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  if("${_nob_diff_bool_value}" MATCHES "-NOTFOUND$")
    set(${out} "0" PARENT_SCOPE)
    return()
  endif()
  set(${out} "1" PARENT_SCOPE)
endfunction()

function(nob_diff_sort_join out)
  set(_nob_diff_items ${ARGN})
  if(_nob_diff_items)
    list(SORT _nob_diff_items)
    string(JOIN ";" _nob_diff_joined ${_nob_diff_items})
  else()
    set(_nob_diff_joined "")
  endif()
  set(${out} "${_nob_diff_joined}" PARENT_SCOPE)
endfunction()

function(nob_diff_report_append_line path line)
  nob_diff_normalize_value(_nob_diff_line "${line}")
  file(APPEND "${path}" "${_nob_diff_line}\n")
endfunction()

function(nob_diff_report_append_kv path key value)
  nob_diff_normalize_value(_nob_diff_value "${value}")
  file(APPEND "${path}" "${key}=${_nob_diff_value}\n")
endfunction()
