cmake_minimum_required(VERSION 3.28)

include("${CMAKE_CURRENT_LIST_DIR}/__nob_diff_oracle_common.cmake")

if(NOT DEFINED NOB_DIFF_SOURCE_DIR OR
   NOT DEFINED NOB_DIFF_BINARY_DIR OR
   NOT DEFINED NOB_DIFF_REPORT)
  message(FATAL_ERROR "meta graph oracle requires NOB_DIFF_SOURCE_DIR, NOB_DIFF_BINARY_DIR and NOB_DIFF_REPORT")
endif()

set(CMAKE_SOURCE_DIR "${NOB_DIFF_SOURCE_DIR}")
set(CMAKE_BINARY_DIR "${NOB_DIFF_BINARY_DIR}")
set(CMAKE_CURRENT_SOURCE_DIR "${NOB_DIFF_SOURCE_DIR}")
set(CMAKE_CURRENT_BINARY_DIR "${NOB_DIFF_BINARY_DIR}")

function(_nob_diff_meta_append_prelude path)
  set_property(GLOBAL PROPERTY NOB_DIFF_META_EXTERNAL_TARGETS "")
  set(_nob_diff_prelude "${NOB_DIFF_BINARY_DIR}/__oracle/file_api_meta_prelude.txt")
  if(EXISTS "${_nob_diff_prelude}")
    file(READ "${_nob_diff_prelude}" _nob_diff_text)
    string(REPLACE "\r\n" "\n" _nob_diff_text "${_nob_diff_text}")
    string(REPLACE "\r" "\n" _nob_diff_text "${_nob_diff_text}")
    string(REPLACE "\n" ";" _nob_diff_lines "${_nob_diff_text}")
    foreach(_nob_diff_line IN LISTS _nob_diff_lines)
      if(NOT "${_nob_diff_line}" STREQUAL "")
        string(REGEX MATCH "^MSPROJECT:([^:]+):" _nob_diff_msproject_match "${_nob_diff_line}")
        if(_nob_diff_msproject_match)
          set(_nob_diff_external_targets)
          get_property(_nob_diff_external_targets GLOBAL PROPERTY NOB_DIFF_META_EXTERNAL_TARGETS)
          list(APPEND _nob_diff_external_targets "${CMAKE_MATCH_1}")
          list(REMOVE_DUPLICATES _nob_diff_external_targets)
          set_property(GLOBAL PROPERTY NOB_DIFF_META_EXTERNAL_TARGETS "${_nob_diff_external_targets}")
        endif()
        nob_diff_report_append_line("${path}" "${_nob_diff_line}")
      endif()
    endforeach()
  endif()
endfunction()

nob_diff_report_reset("${NOB_DIFF_REPORT}")
_nob_diff_meta_append_prelude("${NOB_DIFF_REPORT}")

set(_nob_diff_reply_dir "${NOB_DIFF_BINARY_DIR}/.cmake/api/v1/reply")
if(NOT EXISTS "${_nob_diff_reply_dir}")
  nob_diff_report_append_kv("${NOB_DIFF_REPORT}" "FILE_API_REPLY_DIR" "0")
  return()
endif()

file(GLOB _nob_diff_index_files "${_nob_diff_reply_dir}/index-*.json")
list(SORT _nob_diff_index_files)
if(NOT _nob_diff_index_files)
  nob_diff_report_append_kv("${NOB_DIFF_REPORT}" "FILE_API_INDEX" "0")
  return()
endif()

nob_diff_report_append_kv("${NOB_DIFF_REPORT}" "FILE_API_INDEX" "1")
list(GET _nob_diff_index_files 0 _nob_diff_index_path)
file(READ "${_nob_diff_index_path}" _nob_diff_index_json)

set(_nob_diff_lines)
string(JSON _nob_diff_reply_len LENGTH "${_nob_diff_index_json}" objects)
math(EXPR _nob_diff_reply_last "${_nob_diff_reply_len} - 1")
foreach(_nob_diff_i RANGE 0 ${_nob_diff_reply_last})
  string(JSON _nob_diff_kind GET "${_nob_diff_index_json}" objects ${_nob_diff_i} kind)
  if(NOT _nob_diff_kind)
    continue()
  endif()
  list(APPEND _nob_diff_lines "REPLY_KIND:${_nob_diff_kind}")
  if(_nob_diff_kind STREQUAL "codemodel")
    string(JSON _nob_diff_json_file GET "${_nob_diff_index_json}" objects ${_nob_diff_i} jsonFile)
    if(NOT _nob_diff_json_file)
      continue()
    endif()
    file(READ "${_nob_diff_reply_dir}/${_nob_diff_json_file}" _nob_diff_codemodel_json)
    string(JSON _nob_diff_cfg_len LENGTH "${_nob_diff_codemodel_json}" configurations)
    if(_nob_diff_cfg_len GREATER 0)
      string(JSON _nob_diff_target_len LENGTH "${_nob_diff_codemodel_json}" configurations 0 targets)
      if(_nob_diff_target_len GREATER 0)
        math(EXPR _nob_diff_target_last "${_nob_diff_target_len} - 1")
        foreach(_nob_diff_ti RANGE 0 ${_nob_diff_target_last})
          string(JSON _nob_diff_target_name GET "${_nob_diff_codemodel_json}" configurations 0 targets ${_nob_diff_ti} name)
          if(_nob_diff_target_name)
            get_property(_nob_diff_external_targets GLOBAL PROPERTY NOB_DIFF_META_EXTERNAL_TARGETS)
            list(FIND _nob_diff_external_targets "${_nob_diff_target_name}" _nob_diff_external_index)
            if(_nob_diff_external_index EQUAL -1)
              list(APPEND _nob_diff_lines "TARGET:${_nob_diff_target_name}")
            endif()
          endif()
        endforeach()
      endif()
    endif()
  endif()
endforeach()

list(REMOVE_DUPLICATES _nob_diff_lines)
list(SORT _nob_diff_lines)
foreach(_nob_diff_line IN LISTS _nob_diff_lines)
  nob_diff_report_append_line("${NOB_DIFF_REPORT}" "${_nob_diff_line}")
endforeach()
