include("${CMAKE_CURRENT_LIST_DIR}/__nob_diff_oracle_common.cmake")

function(nob_diff_pkg_reset_report path)
  nob_diff_report_reset("${path}")
  set_property(GLOBAL PROPERTY NOB_DIFF_PACKAGES_FOUND "")
  set_property(GLOBAL PROPERTY NOB_DIFF_PACKAGES_NOT_FOUND "")
endfunction()

function(nob_diff_pkg_capture path pkg)
  set(_nob_diff_components ${ARGN})
  set(_nob_diff_found_value "${${pkg}_FOUND}")
  set(_nob_diff_dir_value "${${pkg}_DIR}")
  set(_nob_diff_config_value "${${pkg}_CONFIG}")
  set(_nob_diff_mode_hint_value "${${pkg}_MODE_HINT}")
  set(_nob_diff_version_ok_value "${${pkg}_VERSION_OK}")

  nob_diff_bool(_nob_diff_found "${_nob_diff_found_value}")

  set(_nob_diff_mode "NOTFOUND")
  string(LENGTH "${_nob_diff_mode_hint_value}" _nob_diff_mode_hint_len)
  if("${_nob_diff_found}" STREQUAL "1")
    if(_nob_diff_mode_hint_len GREATER 0)
      string(TOUPPER "${_nob_diff_mode_hint_value}" _nob_diff_mode)
    else()
      set(_nob_diff_mode "MODULE")

      string(LENGTH "${_nob_diff_config_value}" _nob_diff_config_len)
      if(_nob_diff_config_len GREATER 0)
        string(FIND "${_nob_diff_config_value}" "provider://" _nob_diff_provider_pos)
        if(_nob_diff_provider_pos EQUAL 0)
          set(_nob_diff_mode "PROVIDER")
        endif()
      endif()

      if("${_nob_diff_mode}" STREQUAL "MODULE")
        string(LENGTH "${_nob_diff_dir_value}" _nob_diff_dir_len)
        if(_nob_diff_dir_len GREATER 0)
          string(LENGTH "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}" _nob_diff_redirect_root_len)
          if(_nob_diff_redirect_root_len GREATER 0)
            string(FIND "${_nob_diff_dir_value}" "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}" _nob_diff_redirect_pos)
            if(_nob_diff_redirect_pos EQUAL 0)
              set(_nob_diff_mode "REDIRECT")
            else()
              set(_nob_diff_mode "CONFIG")
            endif()
          else()
            set(_nob_diff_mode "CONFIG")
          endif()
        endif()
      endif()
    endif()
  endif()

  set(_nob_diff_dir "__UNSET__")
  if("${_nob_diff_found}" STREQUAL "1")
    string(LENGTH "${_nob_diff_dir_value}" _nob_diff_dir_value_len)
    if(_nob_diff_dir_value_len GREATER 0)
      set(_nob_diff_dir "${_nob_diff_dir_value}")
    endif()
  endif()
  if("${_nob_diff_dir}" MATCHES "-NOTFOUND$")
    set(_nob_diff_dir "__UNSET__")
  endif()
  if("${_nob_diff_mode}" STREQUAL "MODULE")
    set(_nob_diff_dir "__UNSET__")
  endif()
  if("${_nob_diff_mode}" STREQUAL "PROVIDER")
    set(_nob_diff_dir "__UNSET__")
  endif()
  if("${_nob_diff_mode}" STREQUAL "REDIRECT")
    set(_nob_diff_dir "__UNSET__")
  endif()
  if("${_nob_diff_mode}" STREQUAL "REGISTRY")
    set(_nob_diff_dir "__UNSET__")
  endif()

  set(_nob_diff_version_ok "0")
  if("${_nob_diff_found}" STREQUAL "1")
    set(_nob_diff_version_ok "1")
  endif()
  string(LENGTH "${_nob_diff_version_ok_value}" _nob_diff_version_ok_len)
  if(_nob_diff_version_ok_len GREATER 0)
    nob_diff_bool(_nob_diff_version_ok "${_nob_diff_version_ok_value}")
  endif()

  get_property(_nob_diff_found_list GLOBAL PROPERTY NOB_DIFF_PACKAGES_FOUND)
  get_property(_nob_diff_missing_list GLOBAL PROPERTY NOB_DIFF_PACKAGES_NOT_FOUND)
  if("${_nob_diff_found}" STREQUAL "1")
    list(APPEND _nob_diff_found_list "${pkg}")
    list(REMOVE_ITEM _nob_diff_missing_list "${pkg}")
  else()
    list(APPEND _nob_diff_missing_list "${pkg}")
    list(REMOVE_ITEM _nob_diff_found_list "${pkg}")
  endif()
  list(REMOVE_DUPLICATES _nob_diff_found_list)
  list(REMOVE_DUPLICATES _nob_diff_missing_list)
  set_property(GLOBAL PROPERTY NOB_DIFF_PACKAGES_FOUND "${_nob_diff_found_list}")
  set_property(GLOBAL PROPERTY NOB_DIFF_PACKAGES_NOT_FOUND "${_nob_diff_missing_list}")

  nob_diff_report_append_kv("${path}" "FOUND:${pkg}" "${_nob_diff_found}")
  nob_diff_report_append_kv("${path}" "DIR:${pkg}" "${_nob_diff_dir}")
  nob_diff_report_append_kv("${path}" "MODE:${pkg}" "${_nob_diff_mode}")
  nob_diff_report_append_kv("${path}" "VERSION_OK:${pkg}" "${_nob_diff_version_ok}")
  foreach(_nob_diff_comp IN LISTS _nob_diff_components)
    nob_diff_bool(_nob_diff_comp_found "${${pkg}_${_nob_diff_comp}_FOUND}")
    nob_diff_report_append_kv("${path}"
                              "COMPONENT:${pkg}:${_nob_diff_comp}"
                              "${_nob_diff_comp_found}")
  endforeach()
endfunction()

function(nob_diff_pkg_capture_globals path)
  set(_nob_diff_found "")
  set(_nob_diff_missing "")
  if(ARGN)
    foreach(_nob_diff_pkg ${ARGN})
      nob_diff_bool(_nob_diff_pkg_found "${${_nob_diff_pkg}_FOUND}")
      if("${_nob_diff_pkg_found}" STREQUAL "1")
        list(APPEND _nob_diff_found "${_nob_diff_pkg}")
      else()
        list(APPEND _nob_diff_missing "${_nob_diff_pkg}")
      endif()
    endforeach()
  else()
    get_property(_nob_diff_found GLOBAL PROPERTY NOB_DIFF_PACKAGES_FOUND)
    get_property(_nob_diff_missing GLOBAL PROPERTY NOB_DIFF_PACKAGES_NOT_FOUND)
  endif()
  nob_diff_sort_join(_nob_diff_found_sorted ${_nob_diff_found})
  nob_diff_sort_join(_nob_diff_missing_sorted ${_nob_diff_missing})
  nob_diff_report_append_kv("${path}" "PACKAGES_FOUND" "${_nob_diff_found_sorted}")
  nob_diff_report_append_kv("${path}" "PACKAGES_NOT_FOUND" "${_nob_diff_missing_sorted}")
endfunction()
